### ISSUE TITLE
Gradle Sync dont working

### ISSUE THREAD

**Issue by kaplanerkan** [atzcx/AppVerUpdater#1]
Hello,

i try to use your plugins in my project with following settings;

>  compile 'com.github.atzcx:AppVerUpdater:1.0'

but i get this error;

> Error:Could not find com.github.atzcx:AppVerUpdater:1.0.
> Required by:
>     MyGarson_4..0:app:unspecified
> Search in build.gradle files

i think this is a version problem.
can you please change your version 1.0.0 ? also not 1.0

thanks

**Comment by atzcx** [comment]
Hi,
Add the jitpack repository:
repositories {
      maven { url "https://jitpack.io" }
 }

**Comment by kaplanerkan** [comment]
fixed
i have it so now;

> compile 'com.github.atzcx:AppVerUpdater:1.0.0'

thanks

**Comment by Akshaybil** [comment]
Error:(24, 13) Failed to resolve: com.github.atzcx:AppVerUpdater:1.0.10
<a href="openFile">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a> I am getting this error. please help
