### ISSUE TITLE
UpdateModel.getVersion() -> Nullpointer

### ISSUE THREAD

**Issue by kaplanerkan** [atzcx/AppVerUpdater#2]
Hi,

i get following Error;

> 01-09 16:00:01.746 17580-17580/com.mtt8.mygarson4.pda E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                         Process: com.mtt8.mygarson4.pda, PID: 17580
>                                                                         java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.github.atzcx.appverupdater.models.UpdateModel.getVersion()' on a null object reference
>                                                                             at com.github.atzcx.appverupdater.AppVerUpdater$1.onSuccess(AppVerUpdater.java:103)
>                                                                             at com.github.atzcx.appverupdater.utils.UtilsAsyncTask$JSONAsyncTask.onPostExecute(UtilsAsyncTask.java:101)
>                                                                             at com.github.atzcx.appverupdater.utils.UtilsAsyncTask$JSONAsyncTask.onPostExecute(UtilsAsyncTask.java:24)
>                                                                             at android.os.AsyncTask.finish(AsyncTask.java:632)
>                                                                             at android.os.AsyncTask.access$600(AsyncTask.java:177)
>                                                                             at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
>                                                                             at android.os.Handler.dispatchMessage(Handler.java:106)
>                                                                             at android.os.Looper.loop(Looper.java:189)
>                                                                             at android.app.ActivityThread.main(ActivityThread.java:5529)
>                                                                             at java.lang.reflect.Method.invoke(Native Method)
>                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
>                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956)
>                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)

i start it so;

>             new AppVerUpdater(Main.this)
>                     .setJSONUrl("http://192.168.1.188/androidapis/pda_update.json")
>                     .setDialogTitle("Availabe a new update!")
>                     .setDialogContent("Update %s mobile app to version %s \nFeatures: \n%s")
>                     .setDialogPositiveText("Update")
>                     .setDialogNegativeText("Later")
>                     .setProgressDialogMessage("Download updates...")
>                     .build();

**Comment by atzcx** [comment]
Hi. try again I made new changes, thank you

**Comment by kaplanerkan** [comment]
i try it to start so;

>   new AppVerUpdater(Main.this)
>                     .setUpdateJSONUrl("http://192.168.1.188/androidapis/pda_update.json")
>                     .setAlertDialogTitle("Availabe a new update!")
>                     .setAlertDialogContent("Update %s mobile app to version %s \nFeatures: \n%s")
>                     .setAlertDialogPositiveText("Update")
>                     .setAlertDialogNegativeText("Later")
>                     .setProgressDialogMessage("Download updates...")
>                     .build();

But AlertDialog dont show...Only see following on console;


>  Update: UpdateModel{version='5.0.7', url='http://localhost/androidapis/pda_5.0.7.apk', notes='- Bug fixes

                                                                       '}

**Comment by kaplanerkan** [comment]
i changed my json but get nothing;

> {
>   "newVersion": "5.0.7",
>   "apkUrl": "http://192.168.1.188/androidapis/pda_5.0.7.apk",
>   "versionNotes": [
>     "- Bug fixes"
>   ]
> }

AlertDialog dont show nothing...only on console;

>  Update: UpdateModel{version='5.0.7', url='http://192.168.1.188/androidapis/pda_5.0.7.apk', notes='- Bug fixes

                                                                       '}

**Comment by atzcx** [comment]
the current version of the application, what?

**Comment by kaplanerkan** [comment]
yes, i have defined this version in build.gradle:

>    compile 'com.github.atzcx:AppVerUpdater:1.0.0'

**Comment by atzcx** [comment]
the build.gradle versionName what?

**Comment by kaplanerkan** [comment]
>  classpath 'com.android.tools.build:gradle:2.2.3'

**Comment by atzcx** [comment]
```
defaultConfig { 
 versionName: ?
}

```

**Comment by kaplanerkan** [comment]
>     defaultConfig {
>         applicationId "com.mtt8.mygarson4.pda"
>         minSdkVersion 21
>         targetSdkVersion 25
>         versionCode 5
>         versionName "5.0.7"
> 
>     }

**Comment by kaplanerkan** [comment]
installed Version and apk Version is same.
you mean it s problem?

**Comment by atzcx** [comment]
yes, installed Version and newVersion must be different,

Example: versionName "1.5.0"  
newVersion "5.0.7" 

then AlertDialog show.

**Comment by kaplanerkan** [comment]
i change the versionName to 5.0.9 and buid a APK (dont installed on samsung devices.)

>     defaultConfig {
>         applicationId "com.mtt8.mygarson4.pda"
>         minSdkVersion 21
>         targetSdkVersion 25
>         versionCode 5
>         versionName "5.0.9"

**json;**

> {
>   "newVersion": "5.0.9",
>   "apkUrl": "http://192.168.1.188/androidapis/pda_update.apk",
>   "versionNotes": [
>     "- Bug fixes"
>   ]
> }


onClick on Button show following ErrorMessage;

 Update: UpdateModel{version='5.0.9', url='http://192.168.1.188/androidapis/pda_update.apk', notes='- Bug fixes
                                                                       '}

> 01-09 17:20:54.392 27660-27660/com.mtt8.mygarson4.pda D/AndroidRuntime: Shutting down VM
> 01-09 17:20:54.405 27660-27660/com.mtt8.mygarson4.pda E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                         Process: com.mtt8.mygarson4.pda, PID: 27660
>                                                                         java.util.MissingFormatArgumentException: Format specifier: s
>                                                                             at java.util.Formatter.getArgument(Formatter.java:1111)
>                                                                             at java.util.Formatter.doFormat(Formatter.java:1076)
>                                                                             at java.util.Formatter.format(Formatter.java:1042)
>                                                                             at java.util.Formatter.format(Formatter.java:1011)
>                                                                             at java.lang.String.format(String.java:1803)
>                                                                             at java.lang.String.format(String.java:1777)
>                                                                             at com.github.atzcx.appverupdater.AppVerUpdater.formatContent(AppVerUpdater.java:155)
>                                                                             at com.github.atzcx.appverupdater.AppVerUpdater.access$300(AppVerUpdater.java:16)
>                                                                             at com.github.atzcx.appverupdater.AppVerUpdater$1.onSuccess(AppVerUpdater.java:117)
>                                                                             at com.github.atzcx.appverupdater.AsyncRequest$JSONAsyncTask.onPostExecute(AsyncRequest.java:102)
>                                                                             at com.github.atzcx.appverupdater.AsyncRequest$JSONAsyncTask.onPostExecute(AsyncRequest.java:25)
>                                                                             at android.os.AsyncTask.finish(AsyncTask.java:632)
>                                                                             at android.os.AsyncTask.access$600(AsyncTask.java:177)
>                                                                             at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
>                                                                             at android.os.Handler.dispatchMessage(Handler.java:106)
>                                                                             at android.os.Looper.loop(Looper.java:189)
>                                                                             at android.app.ActivityThread.main(ActivityThread.java:5529)
>                                                                             at java.lang.reflect.Method.invoke(Native Method)
>                                                                             at java.lang.reflect.Method.invoke(Method.java:372)
>                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956)
>                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)

**Comment by kaplanerkan** [comment]
I think you must define your String.format;

xxxxxxxxxx.String.format("%s",xxxxxxxxxxxxxxx

**Comment by atzcx** [comment]
Hi, fixed crash
`compile 'com.github.atzcx:AppVerUpdater:1.0.1'`
