### ISSUE TITLE
Android Nougat Crash

### ISSUE THREAD

**Issue by fcannizzaro** [atzcx/AppVerUpdater#3]
```
android.os.FileUriExposedException:
file:///storage/emulated/0/update-2017-01-09.apk exposed beyond app through Intent.getData()
```

In Android > 7 you should use a FileProvider after the download is completed to run the installer.

**Comment by atzcx** [comment]
Hi, fixed crash
`compile 'com.github.atzcx:AppVerUpdater:1.0.1'`

**Comment by fcannizzaro** [comment]
👍 Thanks
