### ISSUE TITLE
If up to date no popup

### ISSUE THREAD

**Issue by Rab3020** [atzcx/AppVerUpdater#4]
Hello, If the app is up to date there is no pop up saying It is up to date and many of the user may thing the button is not working If the app is up to date. please add a pop up saying App up to date! when there is no update. thank you.

**Comment by Rab3020** [comment]
Okay 1 more ISSUE when you change the url for update from your default url It does not download :/ please fix.

**Comment by atzcx** [comment]
Hi, fixed crash

`compile 'com.github.atzcx:AppVerUpdater:1.0.1'`

```Java
new AppVerUpdater(this)
    .setUpdateJSONUrl("http://example.com/update.json")
    .setShowNotUpdated(true) //Show Dialog Is Not Update
    .setViewNotes(true)
    .build();
```
