### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Rab3020** [atzcx/AppVerUpdater#6]
private void start(){
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N){
            new TedPermission(context)
                    .setPermissionListener(permissionListener)
                    .setDeniedMessage(String.valueOf(denied_message))
                    .setDeniedCloseButtonText(android.R.string.ok)
                    .setGotoSettingButton(false)
                    .setPermissions(Manifest.permission.WRITE_EXTERNAL_STORAGE)
                    .check();
        } else {
            update();
        }
    }

error on this code. the N is highlited Red

**Comment by Rab3020** [comment]
Line still not fixed for me

**Comment by atzcx** [comment]
Hi, update version library

`compile 'com.github.atzcx:AppVerUpdater:1.0.2'`

**Comment by Rab3020** [comment]
Oh thank you :)
