### ISSUE TITLE
Error Null Pointer Exception

### ISSUE THREAD

**Issue by Slayer91** [atzcx/AppVerUpdater#8]
This error occurred when the download was about 5%  - it is possible the network dropped out.

![image](https://cloud.githubusercontent.com/assets/11078018/22063834/da4063c0-dd78-11e6-8e58-984011c695c7.png)

**Comment by atzcx** [comment]
Hi, new version of the library, 
`compile 'com.github.atzcx:AppVerUpdater:1.0.3'`

**Comment by Slayer91** [comment]
That has worked great thanks. Good work!
