### ISSUE TITLE
No way of monitoring if download was successful or not.

### ISSUE THREAD

**Issue by Slayer91** [atzcx/AppVerUpdater#9]
If the connection drops while downloading no error is displayed. Also there is not callback or listener that I can attach to, so i cannot tell if it has finished successfully.

**Comment by atzcx** [comment]
Hi, thanks for the tip, be sure to fix

**Comment by Slayer91** [comment]
Look forward to it

**Comment by atzcx** [comment]
Hi, update the version of the library
`compile 'com.github.atzcx:AppVerUpdater:1.0.4'`

Basic Usage

```Java
new AppVerUpdater(MainActivity.this)
                .setUpdateJSONUrl("http://example.com/updateinfo.json")
                .setShowNotUpdated(true)
                .setViewNotes(false)
                .setCallback(new Callback() {
                    @Override
                    public void onFailure(AppVerUpdaterError error) {
                        if (error == AppVerUpdaterError.NETWORK_NOT_AVAILABLE){
                            Toast.makeText(MainActivity.this, "No Internet Connection", Toast.LENGTH_LONG).show();
                        } else if (error == AppVerUpdaterError.NETWORK_DISKONNECTED){
                            Toast.makeText(MainActivity.this, "Internet Disconnected", Toast.LENGTH_LONG).show();
                        }
                        //Toast.makeText(MainActivity.this, "update erro: " + error, Toast.LENGTH_LONG).show();
                    }
                })
                .build();
```

**Comment by Slayer91** [comment]
Perfect! Will try it out

**Comment by Slayer91** [comment]
This error has come back. It was resolved in 1.0.3
 
![image](https://cloud.githubusercontent.com/assets/11078018/22200787/7d6b3ec0-e158-11e6-8254-6d094c4b9a83.png)

**Comment by atzcx** [comment]
Hi, update the version of the library
compile 'com.github.atzcx:AppVerUpdater:1.0.5'

**Comment by Slayer91** [comment]
Great! now it is working and catches and gives error if I unplug and/or doesn't have internet but it does not catch a fail if there is a SocketTimeoutException
![image](https://cloud.githubusercontent.com/assets/11078018/22205797/43e145ba-e170-11e6-9b0d-83e191a3250d.png)


This does not hit onFailure.

Also DISKONNECTED is spelt DISCONNECTED

**Comment by atzcx** [comment]
Hi, update the version of the library
`compile 'com.github.atzcx:AppVerUpdater:1.0.6'`

all error messages
```Java
UpdateErrors.NETWORK_NOT_AVAILABLE
UpdateErrors.NETWORK_DISCONNECTED
UpdateErrors.SOCET_TIMEOUT_EXCEPTION
UpdateErrors.UNKNOWN_HOST_EXCEPTION
UpdateErrors.SOCET_EXCEPTION
UpdateErrors.STRING_URL_IS_EMPTY
UpdateErrors.JSON_FILE_IS_MISSING
UpdateErrors.FILE_JSON_NO_DATA
```
Added errors handling, as you requested. Thanks for the help

**Comment by Slayer91** [comment]
Will test now. Thank You

**Comment by Slayer91** [comment]
This is more info. I do not get the onFailure call when there is a SocketTimeoutException. I have debugged it in the AsyncClient class and it hits the catch however it does not call back to the onFailure.
![image](https://cloud.githubusercontent.com/assets/11078018/22245621/c0184f1c-e228-11e6-8fb9-c9819e431e61.png)

Am I doing something wrong?
Also Note that "Socet" is spelt "Socket"

**Comment by atzcx** [comment]
Hi, everything seems to be fixed, you can use. Update the version of the library

`compile 'com.github.atzcx:AppVerUpdater:1.0.7'`

[MainActivity.java](https://github.com/atzcx/AppVerUpdater/blob/master/app/src/main/java/com/github/atzcx/appverupdater/sample/MainActivity.java)

if that I will be glad to help

**Comment by Slayer91** [comment]
Will test tomorrow thanks
